In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [3]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
X_train_std = standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [ ]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [6]:
# Aplicamos los métodos "fit" y "transform" por separado
f = standardizer.fit(X_train)
X_trained = f.transform(X_train)

In [7]:
# Comprobar si las matrices estandarizadas son iguales
print(np.array_equiv(X_train_std, X_trained))

True
